<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reserva[
<!ELEMENT reserva (nombre,telefono,email,fecha,personas,presupuesto,comentarios)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT presupuesto (#PCDATA)>
<!ELEMENT comentarios (#PCDATA)>
]>


<reserva>
    <nombre>uyhadh</nombre>
    <telefono>79823749</telefono>
    <email>lskjlkjasf</email>
    <fecha>12/12/12</fecha>
    <personas>12</personas>
    <presupuesto>23</presupuesto>
    <comentarios>ajksdhflk</comentarios>       
</reserva>

